### ISSUE TITLE
Freyja demix ending up in Errors

### ISSUE THREAD

**Issue by lifehashopes** [andersen-lab/Freyja#110]
Hi Everyone,

I am trying to run Freyja on my wastewater SARS-CoV-2 data. I am able to call variants and generate depth files from my primer trimmed bam files.
but freyja demix is giving following error,

freyja demix testvariant.tsv testdepth 
building mix/depth matrices
demixing
Traceback (most recent call last):
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'log2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uadmin/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 73, in demix
    sample_strains, abundances, error = solve_demixing_problem(df_barcodes,
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/sample_deconv.py", line 129, in solve_demixing_problem
    dep = np.log2(depths+1)
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/generic.py", line 2113, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/home/uadmin/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/arraylike.py", line 402, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type Series which has no callable log2 method

Thanks for the help in advance!

Due to size of the files, I have provided one drive link to depth and variant file,

https://1drv.ms/u/s!Aij87x953VLAk9NvYued2nYRazFeYw?e=tsDiEp

**Comment by joshuailevy** [comment]
Hi @lifehashopes! 

Just took a look at your variant and depth files, and it looks like you've got quite a few non-SARS-CoV-2 things in your sample that may be causing some issues, since freyja is expecting just one reference genome. Does this still happen when you specify the name of your desired reference using the ```--refname``` option in ```freyja variants```?

**Comment by luhugerth** [comment]
I had the same issue as @lifehashopes and can confirm that using the `--refname` flag solves the issue (and also makes `freyja variants` run a lot faster) :+1:

**Comment by joshuailevy** [comment]
Great, thanks @luhugerth! Going to close this then!
