### ISSUE TITLE
KeyError Freyja demix (Lofreq vcf)

### ISSUE THREAD

**Issue by LauraVP1994** [andersen-lab/Freyja#119]
Dear,

I used the lofreq output which we want to use in the feyja demix tool. However, I used this command

`freyja demix SC-23-06-A-43-rep-1-S21_L001_pos_q.vcf SC-23-06-A-43-rep-1-S21_L001.depth --output SC-23-06-A-43-rep-1-S21_L001.demix`

and I get this error:

```
building mix/depth matrices
Traceback (most recent call last):
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 29700

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lavanpoelvoorde/miniconda3/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/freyja/_cli.py", line 69, in demix
    mix, depths_, cov = build_mix_and_depth_arrays(variants, depths, muts,
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/freyja/sample_deconv.py", line 51, in build_mix_and_depth_arrays
    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\d+', kI)[0]), 3]
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/freyja/sample_deconv.py", line 51, in <dictcomp>
    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\d+', kI)[0]), 3]
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 960, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3622, in _get_value
    row = self.index.get_loc(index)
  File "/home/lavanpoelvoorde/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 29700
```
When I compare my input files with the other issues, it does seem to be similar so I'm not sure what is going wrong?

I added the depth file, the lofreq vcf file and the fasta (reference) file (added the txt to comply with github). The depth file was constructed according what was suggested in the README.
[SC-23-06-A-43-rep-1-S21_L001.depth.txt](https://github.com/andersen-lab/Freyja/files/10919326/SC-23-06-A-43-rep-1-S21_L001.depth.txt)
[SC-23-06-A-43-rep-1-S21_L001.fasta.txt](https://github.com/andersen-lab/Freyja/files/10919327/SC-23-06-A-43-rep-1-S21_L001.fasta.txt)
[SC-23-06-A-43-rep-1-S21_L001_pos_q.vcf.txt](https://github.com/andersen-lab/Freyja/files/10919328/SC-23-06-A-43-rep-1-S21_L001_pos_q.vcf.txt)

**Comment by LauraVP1994** [comment]
I have been looking what exactly the problem is and it seems that the problem was that the depth file didn't go until 29903 but only 29687. If I added these with depth 0 it seemed to be solved.

**Comment by joshuailevy** [comment]
Hey @LauraVP1994, that's a good catch regarding the depth file not going all the way up to 29903. It seems you might have an issue with your mpileup command then, perhaps an issue with your reference (should be standard Hu-1)?  Does this happen on all of your samples? or just a subset?

**Comment by LauraVP1994** [comment]
Indeed, we found the documentation at first not very clear what input was necessary. We had initially used a BAM file that was generated by our viral pipeline that looks for the closest reference to map against and construct the consensus sequence. The Lofreq file was also called against the consensus sequence. We guess what should be the input it a BAM file called against the Hu-1 reference and Lofreq (or iVar) called against the reference so that the consensus mutations are also in this file?

**Comment by joshuailevy** [comment]
Ah, that slight difference in alignment approach could definitely be causing the issue. As you suggest, you'll want to align against the Hu-1 reference and then use either LoFreq or iVar to do the SNV calling. You can also do this directly within Freyja via the ```freyja variants``` command, which will produce both an iVar output and an mpileup outputted file containing all of the read depths. 

thanks for bringing this up. I'll work on making the documentation a bit clearer on this point.
