### ISSUE TITLE
Unexpected solver error, only when using May 4th 2023 database

### ISSUE THREAD

**Issue by algaraber** [andersen-lab/Freyja#137]
Hello:

I ran into an issue the other day while running freyja demix; the program throws an error and exits ("cvxpy.error.SolverError: 'ECOS' Solver failed"). This is surprising because freyja processed all other samples in this dataset, generated by the same means, without any issues. What is more surprising is that this occurred only on the 4th of May; when we updated the barcodes database the next time we ran freyja, the program ran on the same sample without any issues. However, the problem is replicable, and when one specifically uses the barcodes from the 4th of May to analyse the sample, the same error comes up. Is there any specific reason this could happen?

I include the command used below, the error, and links to the version of the barcodes database with which the issue occurs. Note that the ECOS solver has been used in verbose mode in an attempt to troubleshoot.

Any insights are appreciated
Thank you!

Command used:

```
# This command is run as part of a loop where the variable j is the name of the sample
freyja demix "${outdir}/freyja/${j}_var.tsv" "${outdir}/freyja/${j}_depth" --barcodes "barcodes_04-05-23/usher_barcodes.csv" --output "${outdir}/freyja/mixtures/${j}_mix"
```

Outcome:

```
demixing
===============================================================================
                                     CVXPY                                     
                                     v1.3.1                                    
===============================================================================
(CVXPY) May 12 01:22:32 PM: Your problem has 2481 variables, 2 constraints, and 0 parameters.
(CVXPY) May 12 01:22:32 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 12 01:22:32 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 12 01:22:32 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) May 12 01:22:32 PM: Compiling problem (target solver=ECOS).
(CVXPY) May 12 01:22:32 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) May 12 01:22:32 PM: Applying reduction Dcp2Cone
(CVXPY) May 12 01:22:32 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 12 01:22:32 PM: Applying reduction ConeMatrixStuffing
(CVXPY) May 12 01:22:32 PM: Applying reduction ECOS
(CVXPY) May 12 01:22:32 PM: Finished problem compilation (took 3.174e-01 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) May 12 01:22:32 PM: Invoking solver ECOS  to obtain a solution.

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +1.796e-16  +7.958e-14  +3e+04  1e+00  7e-01  1e+00  2e+00    ---    ---    1  2  - |  -  - 
 1  +2.503e+00  +4.162e+00  +2e+04  5e-01  2e-01  2e+00  1e+00  0.6022  3e-01   2  1  1 |  0  0
 2  +4.358e+00  +5.101e+00  +4e+03  2e-01  3e-02  8e-01  3e-01  0.9125  2e-01   2  1  1 |  0  0
 3  +5.902e+00  +6.395e+00  +3e+03  2e-01  2e-02  5e-01  2e-01  0.3441  3e-01   1  1  1 |  0  0
 4  +7.327e+00  +7.470e+00  +1e+03  1e-01  1e-02  2e-01  1e-01  0.7400  4e-01   1  1  1 |  0  0
 5  +8.077e+00  +8.139e+00  +8e+02  8e-02  7e-03  7e-02  6e-02  0.5666  2e-01   1  1  1 |  0  0
 6  +8.325e+00  +8.348e+00  +5e+02  5e-02  4e-03  3e-02  4e-02  0.6268  5e-01   1  1  1 |  0  0
 7  +8.622e+00  +8.634e+00  +3e+02  3e-02  3e-03  2e-02  2e-02  0.4779  1e-01   1  1  1 |  0  0
 8  +8.677e+00  +8.684e+00  +2e+02  2e-02  2e-03  1e-02  2e-02  0.4119  5e-01   2  1  1 |  0  0
 9  +8.851e+00  +8.852e+00  +8e+01  7e-03  7e-04  2e-03  6e-03  0.8320  2e-01   2  1  1 |  0  0
10  +8.905e+00  +8.905e+00  +5e+01  5e-03  4e-04  1e-03  4e-03  0.4637  2e-01   3  1  1 |  0  0
11  +8.946e+00  +8.946e+00  +2e+01  2e-03  1e-04  2e-04  1e-03  0.9511  3e-01   2  1  1 |  0  0
12  +8.967e+00  +8.967e+00  +5e+00  5e-04  4e-05  6e-05  4e-04  0.7371  3e-02   2  1  1 |  0  0
13  +8.971e+00  +8.971e+00  +3e+00  3e-04  3e-05  4e-05  2e-04  0.5688  3e-01   2  2  2 |  0  0
14  +8.974e+00  +8.974e+00  +1e+00  1e-04  1e-05  2e-05  1e-04  0.7280  3e-01   3  1  1 |  0  0
15  +8.975e+00  +8.975e+00  +9e-01  8e-05  7e-06  9e-06  7e-05  0.7024  4e-01   3  1  1 |  0  0
16  +8.976e+00  +8.976e+00  +5e-01  5e-05  4e-06  5e-06  4e-05  0.9098  5e-01   3  1  1 |  0  0
17  +8.976e+00  +8.976e+00  +4e-02  4e-06  3e-07  4e-07  3e-06  0.9464  3e-02   3  1  1 |  0  0
18  +8.977e+00  +8.977e+00  +4e-04  4e-08  4e-09  5e-09  4e-08  0.9890  1e-04   3  1  1 |  0  0
19  -1.651e+117  +8.977e+00  +5e-06  5e-01  8e-07  5e-11  4e-10  0.9890  1e-04   0  0  0 |  0  0
Unreliable search direction detected, recovering best iterate (18) and stopping.

NUMERICAL PROBLEMS (reached feastol=4.4e-08, reltol=5.0e-05, abstol=4.5e-04).
Runtime: 3.077274 seconds.

Traceback (most recent call last):
  File "/home/afs622/miniconda3/envs/freyja1.3.12/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/freyja/_cli.py", line 73, in demix
    sample_strains, abundances, error = solve_demixing_problem(df_barcodes,
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/freyja/sample_deconv.py", line 139, in solve_demixing_problem
    prob.solve(verbose=True)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 493, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1068, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/home/afs622/miniconda3/envs/freyja1.3.12/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1393, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
```

Version of barcode database used when error happens:
https://github.com/andersen-lab/Freyja/blob/c9e194aadad6648a6a23343e581cf308f8be49f8/freyja/data/usher_barcodes.csv

**Comment by dylanpilz** [comment]
Hello,

Thanks for reaching out and providing the verbose output! There could be a number of things going wrong here related to solver parameters or scaling of the data. Would you mind linking the specific sample that caused the error?
-Dylan

**Comment by skunklem** [comment]
I've had the same problem with some of my samples, so I'll go ahead and share an offending file for you to look at. I also just updated freyja yesterday to v1.4.3, so it has whatever data came in with that release. The same problem has been happening with older datasets as well. The commands used were those from the [C-WAP ](https://github.com/CFSAN-Biostatistics/C-WAP):
```
freyja variants resorted.bam --variants freyja.variants.tsv --depths freyja.depths.tsv --ref C-WAP/covidRefSequences/wuhan.fa
freyja demix freyja.variants.tsv freyja.depths.tsv --output freyja.demix --confirmedonly &
freyja boot freyja.variants.tsv freyja.depths.tsv --nt $(nproc) --nb 1000 --output_base freyja_boot
wait
```

Here's the bam file I was using, all zipped up: [resorted.zip](https://github.com/andersen-lab/Freyja/files/11498229/resorted.zip)
That specific reference fasta is [here](https://github.com/CFSAN-Biostatistics/C-WAP/blob/main/covidRefSequences/wuhan.fa).
My stack trace is actually different from the one here, so I'm not certain our issues are the same, but it ends with the same `cvxpy.error.SolverError...` line. Thanks for looking into this.

**Comment by algaraber** [comment]
Hello:
Apologies for the delay; here are the file with the mapped, trimmed and sorted reads, as well as the reference genome.
Thank you

[MN908947.3.zip](https://github.com/andersen-lab/Freyja/files/11509714/MN908947.3.zip)

[C_S43_L001.mapped.primertrimmed.sorted.zip](https://github.com/andersen-lab/Freyja/files/11509650/C_S43_L001.mapped.primertrimmed.sorted.zip)

**Comment by skunklem** [comment]
Thanks for checking that out. I noticed after sending that sample's bam file that it had fewer reads than most of the other samples and wondered if that could be the issue. This is good to know.
