### ISSUE TITLE
freyja plot error

### ISSUE THREAD

**Issue by rgn3210** [andersen-lab/Freyja#139]
Hello!

When I try to make a plot using the input:
```
freyja plot /home/user/Desktop/wastewater_test/output_directory/aggregated-filename.tsv --output /home/user/Desktop/wastewater_test/output_directory/plot-filename.pdf
```

I get the error:

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 375, in plot
    makePlot_simple(agg_df, lineages, output, config, lineage_info)
  File "/home/user/miniconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py", line 328, in makePlot_simple
    df_abundances = df_abundances.append(
  File "/home/user/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```
What could be the issue? 

this is my aggregated file: 
[aggregated-filename.txt](https://github.com/andersen-lab/Freyja/files/11497191/aggregated-filename.txt)

Thank you !

**Comment by dylanpilz** [comment]
Hey,

In pandas [2.0.0](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html) `DataFrame.append` was deprecated in favor of `pd.concat`. Since the current version of Freyja installs with pandas 2.0.1, it's raising an error when using the deprecated `DataFrame.append` 

A simple work-around would be reverting to pandas version 1.5.3 or earlier while we work on a fix.

-Dylan
