### ISSUE TITLE
Aggregation issue

### ISSUE THREAD

**Issue by CynthiaGibas** [andersen-lab/Freyja#19]
I installed Freyja yesterday afternoon using conda. The variants and demix steps worked fine.

I now have all of my output files in a single subdirectory called 'demixed'. When I go to aggregate them using the command 'freyja aggregate demixed --output ww-omi-demixed.tsv' (which looks like it is correctly formed per your documentation) I get an error that looks like it traces back to a '/' not being included when a file path was formed, because I do have a file 'demixed/112921-27.demix.out', but obviously ''demixed112921-27.demix.out' is not going to work:

`FileNotFoundError: [Errno 2] No such file or directory: 'demixed112921-27.demix.out'`

Weirdly this is not happening on the first file in the demixed directory, but the 7th.

Any suggestions?

Here's the tl/dr on the traceback:

```
Traceback (most recent call last):
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/freyja/_cli.py", line 105, in aggregate
    df_demix = agg(results)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/freyja/utils.py", line 11, in agg
    index_col=0) for fn in os.listdir(results)]
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/freyja/utils.py", line 11, in <listcomp>
    index_col=0) for fn in os.listdir(results)]
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/Users/cgibas/opt/anaconda3/envs/freyja-env/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'demixed112921-27.demix.out'

```

**Comment by joshuailevy** [comment]
Hi @CynthiaGibas, thanks for letting me know. That is definitely strange that this doesn't happen on the first file. 

Do you get the same error if you run the command with  "demixed/" instead, like ```freyja aggregate demixed/ --output ww-omi-demixed.tsv ```?

**Comment by CynthiaGibas** [comment]
That fixed the issue and we were able to get to plots. Thanks. Still strange that it didn't error on the first file though.

**Comment by joshuailevy** [comment]
Ok, great! I'll add in a check to make sure the file exists :)
