### ISSUE TITLE
cvxpy.error.SolverError: Solver 'ECOS' failed

### ISSUE THREAD

**Issue by EricFournier3** [andersen-lab/Freyja#217]
Hi,

depending on the barcode version we use, we sometime have the following error with the `freyja demix` command;

Traceback (most recent call last):
  File "/data/soft/anaconda/2021-11/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/freyja/_cli.py", line 61, in demix
    sample_strains, abundances, error = solve_demixing_problem(df_barcodes,
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/freyja/sample_deconv.py", line 139, in solve_demixing_problem
    prob.solve(verbose=False)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 1020, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/data/soft/anaconda/2021-11/envs/freyja-env/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 1345, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.

But, for the same sample, when we use different barcode versions, we don't get this error.

For example, with our sample L00709285001 combined with barcode version 2024-03-01 we got the error, but not with versions 2024-02-16 nor 2024-02-02. Other samples in the same freyja run don't have this problem

I have tried with three different freyja versions (1.3.11,  1.4.4 and 1.4.9) and always get the same issus with barcode version 2024-03-01. But with freyja 1.4.9, the error message is 'demix: Solver error encountered, mostlikely due to insufficient sequencing depth.Try increasing the --depthcutoff parameter
[L00709285001_depthout.txt](https://github.com/andersen-lab/Freyja/files/14500591/L00709285001_depthout.txt)
[L00709285001_output_20240202.txt](https://github.com/andersen-lab/Freyja/files/14500593/L00709285001_output_20240202.txt)
[L00709285001_output_20240216.txt](https://github.com/andersen-lab/Freyja/files/14500594/L00709285001_output_20240216.txt)
[L00709285001_variantout.txt](https://github.com/andersen-lab/Freyja/files/14500595/L00709285001_variantout.txt)
'

Note that we also have such an issue with other samples combined with older barcode version

Can you please help us with this?

Thanks

Eric

**Comment by sgsutcliffe** [comment]
My best guess is that the newer version of barcode introduces more potential lineages and more possible mutations which makes it difficult for the model resolve the relative abundances. I
cvxpy.error.SolverError is due to a python module used in Freyja (https://www.cvxpy.org/index.html) for convex optimization problems. I have had similar issues I have not been able to resolve. I consider these samples as 'failed'. I'd reach out to Freyja team to see if they have a solution.

**Comment by joshuailevy** [comment]
Hey @EricFournier3! 

As @sgsutcliffe mentioned, the solver errors are a result of the expanded barcode/lineage library that Freyja is using when estimating abundances -- combined with limited genome coverage, such that there is no available information to distinguish between candidate lineages. Although by default Freyja will return equal abundances of all equally likely lineages (for a small number of lineages), at some point the solver will fail to converge as you've seen. 

I wouldn't call these samples "failed" though- there's still a LOT of useful information, you just need to take the available genome coverage into account. I'd recommend trying out the `--depthcutoff` option as per the error message. Freyja should converge easily- and you'll end up with JN.1.X (lineages in this grouping will be specified in the returned YAML file) at nearly 100% in your sample. 

Josh

**Comment by EricFournier3** [comment]
Ok, great. Thank you Josh. I will try that.

Eric

**Comment by EricFournier3** [comment]
Hi @joshuailevy , 
I have tried using --depthcutoff option but I got a key error in [lineage_data[lin]['alias'
=>
[foueri01@inspq.qc.ca@slurm10p 20240223_ww]$ freyja demix L00714375001_variantout.tsv L00714375001_depthout --barcodes usher_barcodes_2024-03-15.csv --output L00714375001_output --depthcutoff 5
Traceback (most recent call last):
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/freyja/_cli.py", line 132, in demix
    df_barcodes = collapse_barcodes(df_barcodes, df_depth, depthcutoff,
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/freyja/utils.py", line 943, in collapse_barcodes
    pango_aliases = [lineage_data[lin]['alias']
  File "/data/soft/anaconda/2021-11/envs/freyja-env3/lib/python3.10/site-packages/freyja/utils.py", line 943, in <listcomp>
    pango_aliases = [lineage_data[lin]['alias']
KeyError: '**JN.13**'

Also, the strange thing is that **JN.13** doesn't even exists in the usher_barcodes_2024-03-15.csv file

Thanks
Eric

**Comment by joshuailevy** [comment]
Hi @EricFournier3,

It seems like this is due to some mismatching of input files. I just checked, and it looks like JN.13 is in there: https://github.com/andersen-lab/Freyja-data/blob/main/history_barcodes/usher_barcodes03_15_2024-00-49.csv. 
As to the error, I think you're specifying an new version of the barcodes, but not providing a lineage hierarchy file that includes those lineages. To solve this, you'll need to either run `freyja update` to get the updated hierarchy file or grab the appropriate one from here: https://github.com/andersen-lab/Freyja-data/tree/main/history_lineage_hierarchy. 

I'll try to get some better error messages for these sorts of things going- it gets a little tricky with all of these different versions floating around. 

Best, 
Josh

**Comment by joshuailevy** [comment]
Error message now included: https://github.com/andersen-lab/Freyja/pull/219

**Comment by EricFournier3** [comment]
Hi @joshuailevy ,

Sorry for confusion. JN.13 is indeed in our usher_barcodes_2024-03-15.csv
But when I execute
```console
username@slbio00d scripts:~$ demix L00714375001_variantout.tsv L00714375001_depthout --barcodes usher_barcodes_2024-03-15.csv --output L00714375001_output --depthcutoff 5
```
I got KeyError: 'JN.13'

and if I increase cutoff to 50
```console
username@slbio00d scripts:~$ demix L00714375001_variantout.tsv L00714375001_depthout --barcodes usher_barcodes_2024-03-15.csv --output L00714375001_output --depthcutoff 50
```
KeyError: 'HK.13.2.1'

Yet, both lineages are in the barcode file

![usher_barcode_20240315_](https://github.com/andersen-lab/Freyja/assets/15850682/ffe3df4d-e1d6-4668-a397-a6da765279d1)
![usher_barcode_20240315](https://github.com/andersen-lab/Freyja/assets/15850682/e4956c00-687a-472e-98f5-25a1e57278b5)

Best,
Eric

**Comment by EricFournier3** [comment]
.

**Comment by joshuailevy** [comment]
Great! Glad it's working for you in v1.5.0 ( which will come standard with an updated lineage hierarchy file).

Best, 
Josh
