### ISSUE TITLE
aggregate command exiting with UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte`

### ISSUE THREAD

**Issue by wilke** [andersen-lab/Freyja#26]
Running the aggregate command `freyja aggregate AM/ --output AM/AM.aggregate.tsv` on a folder containing out files created with freyja:

`Traceback (most recent call last):
  File "/usr/local/bin/freyja", line 33, in <module>
    sys.exit(load_entry_point('freyja==2021.10', 'console_scripts', 'freyja')())
  File "/usr/local/lib/python3.10/site-packages/click-8.0.3-py3.10.egg/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click-8.0.3-py3.10.egg/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click-8.0.3-py3.10.egg/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click-8.0.3-py3.10.egg/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click-8.0.3-py3.10.egg/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/freyja-2021.10-py3.10.egg/freyja/_cli.py", line 149, in aggregate
    df_demix = agg(results)
  File "/usr/local/lib/python3.10/site-packages/freyja-2021.10-py3.10.egg/freyja/utils.py", line 10, in agg
    allResults = [pd.read_csv(results+fn, skipinitialspace=True, sep='\t',
  File "/usr/local/lib/python3.10/site-packages/freyja-2021.10-py3.10.egg/freyja/utils.py", line 10, in <listcomp>
    allResults = [pd.read_csv(results+fn, skipinitialspace=True, sep='\t',
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1231, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 544, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 633, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1952, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte`

**Comment by joshuailevy** [comment]
Hi @wilke, thanks for letting me know. Do you have files other than the outputs from ```freyja demix``` in the ```AM``` directory? At the moment, the ```aggregate``` function isn't particularly smart and won't be able to handle files that don't conform to the expected format.

**Comment by wilke** [comment]
Thank you. I found a hidden file and deleted it. It seems to work now.
