### ISSUE TITLE
pandas InvalidIndexError when performing freyja aggregate

### ISSUE THREAD

**Issue by evantroendle** [andersen-lab/Freyja#29]
When running freyja aggregate:
freyja aggregate /home/evan/anaconda3/ipynb/SARS-COV2/results/freyja/ --output freyja_aggregated_results.tsv

I get this output:

Traceback (most recent call last):
  File "/home/evan/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 144, in aggregate
    df_demix = agg(results)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py", line 12, in agg
    df_demix = pd.concat(allResults, axis=1).T
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 359, in concat
    return op.get_result()
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 588, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

The folder in question solely contains the following files:
SAMPLE1_freyja_demix.tsv
SAMPLE1_freyja_depth.tsv
SAMPLE1_freyja_variants.tsv
...
SAMPLEN_freyja_demix.tsv
SAMPLEN_freyja_depth.tsv
SAMPLEN_freyja_variants.tsv

**Comment by evantroendle** [comment]
Apologies, after moving the *demix* outputs to a new directory containing only and calling it on that directory, it now works.

Would it be possible to include as an option a wildcard-based input to aggregate to have it search the target directory for *demix.tsv files only to avoid needing a separate directory?

**Comment by joshuailevy** [comment]
Thanks  @evantroendle for the suggestion! I've now incorporated an ```--ext``` option so the user can specify a file extension of their choosing.
