### ISSUE TITLE
Option to specify database directory?

### ISSUE THREAD

**Issue by rpetit3** [andersen-lab/Freyja#33]
Hello! 

Super awesome tool! I was wondering if it would be possible to get an option to specify the location of the downloaded database.

For example 
```
freyja update --database /home/rpetit3/freyjadb
freyja variants <OPTS> --database /home/rpetit3/freyjadb
freyja demix <OPTS> --database /home/rpetit3/freyjadb
```

I ask because I'd like to update the database while using the  Docker container from Staph-B, but I'm running into write permissions
```
docker run --rm -u $(id -u):$(id -g) --entrypoint /bin/bash -v ${PWD}:/data staphb/freyja:latest -c "freyja update"
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zm48iova because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/opt/conda/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
Downloading a new global tree
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 68, in update
    download_tree()
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/updates.py", line 13, in download_tree
    urllib.request.urlretrieve(url, treePath)
  File "/opt/conda/envs/freyja-env/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: '/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/data/public-latest.all.masked.pb.gz'
```

Thank you!

**Comment by joshuailevy** [comment]
Hi @rpetit3! That's a good idea, and something that can definitely be added. Can try to integrate this soon. Perhaps we should get a PR going for this so we can make sure things are working on docker/your system?

**Comment by rpetit3** [comment]
Hi @joshuailevy, 

I've started a PR, let me know what you think!

Cheers,
Robert

**Comment by joshuailevy** [comment]
Hi @rpetit3, thanks for doing that! Just tested it out and it looks good! Changes have been incorporated.

**Comment by rpetit3** [comment]
No problem! Happy to help out! Cheers
