### ISSUE TITLE
No module named 'pandas.concat'

### ISSUE THREAD

**Issue by AnehEf** [andersen-lab/Freyja#40]
Hi Freyja's team, 
Thanks for this amazing tool :-)

I updated freyja using the conda command (Linux, Cinnamon). Since then, I get the following error:
`
Traceback (most recent call last):
  File "/home/anaconda3/envs/SARSCoV2/bin/freyja", line 6, in <module>
    from freyja._cli import cli
  File "/home/anaconda3/envs/SARSCoV2/lib/python3.8/site-packages/freyja/_cli.py", line 3, in <module>
    from freyja.convert_paths2barcodes import parse_tree_paths,\
  File "/home/anaconda3/envs/SARSCoV2/lib/python3.8/site-packages/freyja/convert_paths2barcodes.py", line 1, in <module>
    import pandas.concat as pd
ModuleNotFoundError: No module named 'pandas.concat'
`
I updated pandas, but it didn't help. 
Thanks for your help, 

Adelaide

**Comment by joshuailevy** [comment]
Hi @AnehEf! It seems that something got changed in your ```convert_paths2barcodes.py``` file. The first line should read ```import pandas as pd``` (without the concat). Let me know if that solves your problem!

Josh

**Comment by AnehEf** [comment]
Thanks
