### ISSUE TITLE
Running Freyja in Windows Subsystem for Linux: KeyError: 'REF'

### ISSUE THREAD

**Issue by aminards** [andersen-lab/Freyja#56]
I have been using Freyja on different sample sets, some single source and some from wastewater.  

The single source sample data ran through Freyja with no issues.
The wastewater samples are giving me this error when running `freyja demix `

```
freyja demix /mnt/c/DataDrive/IRandD_ExactID_Covid/OCWN_fastq/Week_1/Wuhan_bam/SNP-Analyze_Conneaut_0411_Week1_SwiftSarsCoV2_BWA_SARS_Wuhan_sort_freyja_variants.tsv /mnt/c/DataDrive/IRandD_ExactID_Covid/
OCWN_fastq/Week_1/Wuhan_bam/SNP-Analyze_Conneaut_0411_Week1_SwiftSarsCoV2_BWA_SARS_Wuhan_sort_freyja_depths.txt --output /mnt/c/DataDrive/IRandD_ExactID_Covid/OCWN_fastq/Week_1/Wuhan_bam/SNP-Analyze_Conneaut_0411_Week1_SwiftSarsCoV2_BWA_
SARS_Wuhan_sort_freyja_demix.txt
```

```
building mix/depth matrices
Traceback (most recent call last):
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'REF'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/minardsmitha/miniconda3/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/freyja/_cli.py", line 55, in demix
    mix, depths_, cov = build_mix_and_depth_arrays(variants, depths, muts,
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/freyja/sample_deconv.py", line 45, in build_mix_and_depth_arrays
    df['mutName'] = df['REF'] + df['POS'].astype(str) + df['ALT']
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/minardsmitha/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'REF'
```

I tried reinstalling Freyja and tried to determine if my issue is the same as issue #50 but I haven't been able to correct the problem.  
Some help figuring this out would be great.

**Comment by joshuailevy** [comment]
Hi @aminards!
Happy to help. Any chance you can send the  variants.tsv file? Seems like it might have some sort of issue. 
Josh

**Comment by joshuailevy** [comment]
Thanks for sending! That looks like an output file from demix actually, and demix won't be able to parse it. It should look like the standard ``ivar variants``` output.

**Comment by aminards** [comment]
You are right!  Apparently another process overwrote my variants files using the same name!  Completely fixable on my end!
