### ISSUE TITLE
Demix run error code

### ISSUE THREAD

**Issue by Pragungrb** [andersen-lab/Freyja#59]
I am trying to run the demix code, however I'm running into this issue? Could it be due to the python version?

ERROR CODE:
Traceback (most recent call last):
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 10124

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 55, in demix
    mix, depths_, cov = build_mix_and_depth_arrays(variants, depths, muts,
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/sample_deconv.py", line 51, in build_mix_and_depth_arrays
    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\d+', kI)[0]), 3]
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/sample_deconv.py", line 51, in <dictcomp>
    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\d+', kI)[0]), 3]
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/indexing.py", line 960, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/frame.py", line 3622, in _get_value
    row = self.index.get_loc(index)
  File "/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 10124

**Comment by gcha31** [comment]
Hi @Pragungrb and @joshuailevy 

I am also getting a similar error while running 'freyja demix'. If you figured out what is causing this, could you please share it with me? I really appreciate any help you can provide.

**My errors:**

Traceback (most recent call last):
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ALT_FREQ'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/freyja/_cli.py", line 56, in demix
    mix, depths_, cov = build_mix_and_depth_arrays(variants, depths, muts,
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/freyja/sample_deconv.py", line 49, in build_mix_and_depth_arrays
    mix = df.loc[list(keptInds), 'ALT_FREQ'].astype(float)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexing.py", line 1140, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexing.py", line 867, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/generic.py", line 3849, in xs
    return self[key]
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/storage/home/hcoda1/1/gcha31/.conda/envs/freyja/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'ALT_FREQ'

**Comment by joshuailevy** [comment]
Hi @gcha31, 
I've seen this error pop up when the input files to ```freyja demix``` are not supplied properly. Definitely make sure that the variants file is supplied first, followed by the depths file (both files are produced by ```freyja variants```. If that still doesn't work, feel free to send those files my way and I can take a look. 
Josh

**Comment by gcha31** [comment]
I appreciate your prompt response!
Instead of using the vcf files produces elsewhere, I used `freyja variants` this time and it ran without issues. Should the variants file and the depth file have the same numbers of rows?
Gyuhyon

**Comment by joshuailevy** [comment]
No problem. 

Great! They will not have the same number of rows. The variants file will only include sites with at least 1 non-reference base in the data. From there, you just need to run ```freyja demix your-variants-file your-depths-file --output your-output-file ```. I also like to throw in the ```--confirmedonly``` flag these days, in order to remove the lineages that haven't officially been added yet but have been proposed on pango.
