### ISSUE TITLE
Problems running update

### ISSUE THREAD

**Issue by hans-vg** [andersen-lab/Freyja#60]
I am getting the following error when running freyja update.

```
Downloading a new global tree
Getting outbreak data
Converting tree info to barcodes
.
Loading input MAT file ./public-latest.all.masked.pb.gz.
Building barcodes from global phylogenetic tree
Traceback (most recent call last):
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/freyja/_cli.py", line 99, in update
    df = pd.read_csv(lineagePath, sep='\t')
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/data/gpfs/assoc/inbre/projects/subhash_verma/covid_wastewater/snakemake_freyja_covidwastewater/.snakemake/conda/932d05727f530c39c2c142d5886fcbf9/lib/python3.10/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './lineagePaths.txt'
```
Looking at the source code, could it be from line 96 in _cli.py?

   ` lineagePath = os.path.join(os.curdir, "lineagePaths.txt")`

Should os.curdir be locDir instead?

Also, in the downstream commands, I don't see a way to configure the "update" directory with the data.  How does freyja know where to look for this data?

Thank you,
-Hans

**Comment by hans-vg** [comment]
If I run the update command not through snakemake, I do see the lineagePaths.txt file being made in my cwd when setting --outdir .

I will just have to run the update command manually before running the pipeline. 

Is there a way to ensure the commands are using the update --outdir directory? Currently, I'm not sure if it is using the one in the conda env or the updated one.

**Comment by joshuailevy** [comment]
Hey Hans, 
Were you able to sort this out? I can add in an additional command if needed, but I don't think it should be necessary. 
Josh

**Comment by hans-vg** [comment]
Yes,  I'll run the update command before running the full pipeline. Easy work around. I'll close this issue.

**Comment by joshuailevy** [comment]
Ok, great! Thanks for letting me know!

**Comment by AmandaBirmingham** [comment]
Hi, @joshuailevy,
I am running into what looks like just the same problem here, although in a slightly different context.  I've installed freyja via conda (following the directions in the readme) on an Amazon Web Services ubuntu 20.04 instance.  However, when I activate the conda environment and try to run `freyja update`, I get what looks to me like the same error message shown above:

```
Downloading a new global tree
Getting outbreak data
Converting tree info to barcodes
/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/data
Loading input MAT file /shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/data/public-latest.all.masked.pb.gz.
Building barcodes from global phylogenetic tree
Traceback (most recent call last):
  File "/shared/workspace/software/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 99, in update
    df = pd.read_csv(lineagePath, sep='\t')
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/shared/workspace/software/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './lineagePaths.txt'
```

Specifying `--outdir` does not affect this.  When I look in the output directory, I see the `public-latest.all.masked.pb.gz` file but not a `lineagePaths.txt` file, so it seems as though it isn't getting created (and thus can't be read :) .  Any thoughts?

**Comment by AmandaBirmingham** [comment]
I also tried running the command that is supposed to produce `lineagePaths.txt` directly, and this is what I saw:

```
> matUtils extract -i /shared/temp/public-latest.all.masked.pb.gz  -C lineagePaths.txt
Loading input MAT file /shared/temp/public-latest.all.masked.pb.gz.
Killed
```

**Comment by AmandaBirmingham** [comment]
Hey @joshuailevy  --right you are, giving it more memory worked like a charm. Thanks!
