### ISSUE TITLE
Issue using --lineages flag with freyja plotting

### ISSUE THREAD

**Issue by BGcoder321** [andersen-lab/Freyja#77]
Hi,

I am having an issue running freyja's plot function with the following command...

`freyja plot --lineages ArgonneOverallPlot.tsv --output ArgonneOverallPlot5day.png --times sampleTimes.csv --interval D --windowsize 5
`

Whenever I attempt to plot using the --lineages flag, I encounter the following issue:

Traceback (most recent call last):
  File "/home/bcg64/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 219, in plot
    makePlot_time(agg_df, lineages, times_df, interval, output,
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py", line 166, in makePlot_time
    agg_df = prepLineageDict(agg_df)
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py", line 21, in prepLineageDict
    .apply(lambda x:
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/home/bcg64/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py", line 22, in <lambda>
    x.replace("'", "")
AttributeError: 'float' object has no attribute 'replace'

Please let me know if you have any recommendations on how to fix this issue!

**Comment by joshuailevy** [comment]
Hi @BGcoder321! 
I've seen this error pop up when one or more of the samples is of poor quality, resulting in no lineages being identified by freyja (you'd see an entry with an empty list '[]'). This leads to a parsing issue during plotting, though I've now fixed this (and will be part of the upcoming release). 

A quick fix for the meantime is to simply drop those poor quality samples from the aggregated output file. 

Hope this helps! 
Josh

**Comment by joshuailevy** [comment]
This should be resolved in Freyja v1.3.9, so I'm going to go ahead and close this issue. Let me know if this still happens with the new version!
