### ISSUE TITLE
freyja update fails within conda environment with Snakemake

### ISSUE THREAD

**Issue by hans-vg** [andersen-lab/Freyja#90]
```
Downloading a new global tree
Getting outbreak data
Converting tree info to barcodes
/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/freyja/data
Loading input MAT file /data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/freyja/data/public-latest.all.masked.pb.gz.
Building barcodes from global phylogenetic tree
Traceback (most recent call last):
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/freyja/_cli.py", line 102, in update
    df = pd.read_csv(lineagePath, sep='\t')
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/data/gpfs/assoc/inbre/hansvg/home/miniconda3/envs/freyja/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './lineagePaths.txt'

```
The update command is able to successfully download the *.pb.gz file.  However, when it tries to convert the file, it fails.

Looking at the source code, it looks like you can potentially update line 100 in __cli.py.

    lineagePath = os.path.join(os.curdir, "lineagePaths.txt")

changed to 

    lineagePath = os.path.join(locDir, "lineagePaths.txt")

This should allow freyja to update using conda within a Snakemake environment.

**Comment by joshuailevy** [comment]
Hi Hans! 

Thanks for bringing this up. At the moment, there's an issue with python not "flushing" the output when I define the path this way for some reason. Not quite sure why this is, but longer term I'll likely be changing the update method to just pull the most updated barcodes from github (updated in real-time via a github action). 

Been away at a conference this week, but will follow up on this soon. 

Josh

**Comment by gholden3** [comment]
I've seen this too using the conda package, but intermittently. Sometimes update works fine.

**Comment by gholden3** [comment]
Is there a workaround for this issue? I'm seeing it in our cloud server: 
`No such file or directory: \'./lineagePaths.txt\'`

**Comment by gholden3** [comment]
I think actually the issue might be you have a race condition

**Comment by gholden3** [comment]
@hans-vg  How much memory do you have available in the environment where you're running the conda package?

**Comment by joshuailevy** [comment]
I think we're ok here, so I'll go ahead and close this
